---

- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_only: yes
    delegate_to: nginx

- name: Install docker
  yum:
    name:
      - docker
    state: installed

- name: docker-py
  pip:
    name: docker-py
  notify:
    - Start Docker Service
