---

- name: Provision EC2 instance
  ec2_instance:
    key_name: "{{ key_name }}"
    security_group: "{{ security_group_ansible.group_id }}"
    image_id: "{{ image_id }}"
    instance_type: t2.micro
    name: "{{ ec2_name }}"
    tags:
      tool: "{{ ansible_tag }}"
  register: ec2
