---

- name: Upload public key to AWS
  ec2_key:
    name: "{{ key_name }}"
    key_material: "{{ lookup('file', '~/.ssh/{{ key_name }}.pub') }}"

- name: Create security group
  ec2_group:
    name: "{{ security_group }}"
    description: "Ansible SG"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on ssh port, not recommended!
      - proto: tcp
        ports:
          - 80
        cidr_ip: 0.0.0.0/0
        rule_desc: open port 80 to public for Nginx
    rules_egress:
      - proto: -1
        from_port: 0
        to_port: 0
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all outgoing traffic
    tags:
      tool: "{{ ansible_tag }}"
  register: security_group_ansible

- name: Provision EC2 instance
  ec2_instance:
    key_name: "{{ key_name }}"
    security_group: "{{ security_group_ansible.group_id }}"
    image_id: "{{ image_id }}"
    instance_type: t2.micro
    name: "{{ ec2_name }}"
    tags:
      tool: "{{ ansible_tag }}"
  register: ec2

