---

- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - role: ec2

- hosts: nginx
  become: yes
  remote_user: ec2-user
  become_user: root
  become_method: sudo
  gather_facts: False
  roles:
    - role: app
